-- CREATE DATABASE DB_TASK_MENAGER;
-- USE DB_TASK_MENAGER;

CREATE TABLE IF NOT EXISTS TB_TASK (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR (60) NOT NULL,
    DESCRIPTION VARCHAR (255) NULL,
    IS_COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_TASK PRIMARY KEY (ID)
);